apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reader
  namespace: mesh-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-reader-role
  namespace: mesh-lab
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
  namespace: mesh-lab
subjects:
  - kind: ServiceAccount
    name: app-reader
    namespace: mesh-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-reader-role