apiVersion: v1
kind: PersistentVolume
metadata:
  name: mesh-lab-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/mesh-lab-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mesh-lab-pvc
  namespace: mesh-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi