apiVersion: v1
kind: serviceAccount
metadata:
  name: orders-sa
  namespace: shop

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orders-config-reader
  namespace: shop
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-config-reader-binding
  namespace: shop
subjects:
- kind: ServiceAccount
  name: orders-sa
  namespace: shop
roleRef:
  kind: Role
  name: orders-config-reader
  namespace: shop
  apiGroup: rbac.authorization.k8s.io