apiVersion: v1
kind: Namespace
metadata:
  name: keda-practice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-demo
  namespace: keda-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-demo
  template:
    metadata:
      labels:
        app: cpu-demo
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-demo
  namespace: keda-practice
spec:
  selector:
    app: cpu-demo
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-demo-so
  namespace: keda-practice
spec:
  scaleTargetRef:
    name: cpu-demo
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 120
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Pods
              value: 2
              periodSeconds: 60
            - type: Percent
              value: 100
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 180
          selectPolicy: Min
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"



# # #### commands to run in terminal ####
# ==================================
# # kubectl apply -f cpu-keda.yaml
# # kubectl get scaledobjects -n keda-practice
# # kubectl get hpa -n keda-practice -w
# # kubectl get pods -n keda-practice -w
# # kubectl describe scaledobject cpu-demo-so -n keda-practice

# # ####Generate load ####
# -==================
# # kubectl run -n keda-practice cpu-load --rm -it --image=busybox -- /bin/sh
# # while true; do wget -q -O- http://cpu-demo.keda-practice.svc.cluster.local; done

# # ### commands to check metrics after load increase ###
# ===================================================
# # kubectl get hpa -n keda-practice
# # kubectl top pods -n keda-practice
# # kubectl get pods -n keda-practice