apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.properties: |
    app.name=demo-app
    app.env=dev
    app.port=8080
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /etc/config/app.properties && sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: app-config



# What happens here
# Kubernetes creates a ConfigMap named app-config
# Inside the Pod, that ConfigMap is mounted at /etc/config
# The file /etc/config/app.properties becomes available inside the container
# Inside container

# You will see:

# /etc/config/app.properties

# Content:

# app.name=demo-app
# app.env=dev
# app.port=8080


