apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns
  namespace: security-lab
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"


# # In Cilium, DNS resolution is treated as network traffic. 
# When using a default deny policy, DNS queries are also blocked. 
# So we must explicitly allow traffic to kube-dns on port 53 and optionally restrict which domain names can be resolved using L7 DNS rules.