apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  username: admin
  password: mysecurepassword
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "ls /etc/secret && cat /etc/secret/username && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret



# What happens here
# Kubernetes creates a Secret named app-secret
# It contains two keys:
# username
# password
# These are mounted as files inside /etc/secret
# Inside container

# You will see files like:

# /etc/secret/username
# /etc/secret/password

# Each file contains the value of that secret key.