apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /data
      name: shared-vol
  volumes:
  - name: shared-vol
    persistentVolumeClaim:
      claimName: efs-pvc