apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany   # 🔥 THIS IS RWX
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi