apiversion: cilium.io/v2
kind: CiliumNetworkPolicy 
metadata:
  name: L4-policy
  namespace: policy-demo
spec:
  endpointSelector:
    matchLabels:
      role: backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        role: frontend
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  egressDeny:
  - toEndpoints:
    - matchLabels:
        role: database
    toPorts:
    - ports:
      - port: "3306"
        protocol: TCP

