apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: rbac-demo


# Case 1: Internal (K8s)
# Pod → API Server → RBAC → Allowed / Denied
# Case 2: External (AWS)
# Pod → ServiceAccount → IAM Role → AWS (SQS/S3)