apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: rbac-demo
spec:
  serviceAccountName: app-sa
  containers:
  - name: app
    image: curlimages/curl:8.8.0
    command: ["sleep", "3600"]